### ISSUE TITLE
Varnish Multi Servers

### ISSUE THREAD

**Issue by thuynh** [FriendsOfSymfony/FOSHttpCache#121]
When multiple servers are defined, upon sending the requests, the actual server ip addresses got lost. 

FOS\HttpCache\ProxyClient\AbstractProxyClient.php

```
private function sendRequests(array $requests) 
{
        $allRequests = array();

        foreach ($requests as $request) {
            foreach ($this->servers as $server) {
                $proxyRequest = $this->client->createRequest(
                    $request->getMethod(),
                    $server . $request->getResource(),
                    $request->getHeaders()
                );

                $allRequests[] = $proxyRequest;
            }
        }

        try {
            $this->client->send($allRequests);
        } catch (GuzzleExceptionCollection $e) {
            $this->handleException($e);
        }
    }
```

**This is what the raw header looks like:**

PURGE /playlist/featured HTTP/1.1
Host: premium.domain.local
X-Forwarded-Domain: premium.domain.local
User-Agent: Guzzle/3.7.0 curl/7.28.1 PHP/5.4.10

PURGE /playlist/featured HTTP/1.1
Host: premium.domain.local
X-Forwarded-Domain: premium.domain.local
User-Agent: Guzzle/3.7.0 curl/7.28.1 PHP/5.4.10

**I am able to get around this for now by creating a custom Varnish client that has almost all the methods required but adding just one tiny thing. It would have been much simpler if the method was protected.**

```
private function sendRequests(array $requests)
{
		$allRequests = array();

		foreach ($requests as $request) {
			foreach ($this->servers as $server) {
				$parts = parse_url($server);
				$proxyRequest = $this->client->createRequest(
					$request->getMethod(),
					$server . $request->getResource(),
					$request->getHeaders()
				);
				$proxyRequest->setHeader('Host', $parts['host']);
				$allRequests[] = $proxyRequest;
			}
		}

		try {
			$this->client->send($allRequests);
		} catch (GuzzleExceptionCollection $e) {
			$this->handleException($e);
		}
}
```

PURGE /playlist/featured HTTP/1.1
X-Forwarded-Domain: premium.domain.local
User-Agent: Guzzle/3.7.0 curl/7.28.1 PHP/5.4.10
Host: 192.168.1.12

PURGE /playlist/featured HTTP/1.1
X-Forwarded-Domain: premium.domain.local
User-Agent: Guzzle/3.7.0 curl/7.28.1 PHP/5.4.10
Host: 192.168.1.13

**Comment by dbu** [comment]
closed because of inactivity. if there are more questions, please reopen.
