### ISSUE TITLE
Better logging of guzzle exceptions

### ISSUE THREAD

**Issue by dbu** [FriendsOfSymfony/FOSHttpCache#122]
It would be nice if we could log a curl request on guzzle exceptions. @cirpo is working on such a tool, see discussion in https://github.com/guzzle/guzzle/issues/737

**Comment by ddeboer** [comment]
We have switched to php-http/adapter for our HTTP client (#173). Unlike Guzzle itself, this library throws no exceptions for 4xx and 5xx response. I think logging should be done not on the Guzzle level, but as a middleware on the php-http/adapter level.

**Comment by dbu** [comment]
i guess with psr-7 the approach indeed should be a logging middleware. should actually be quite simple - the only challenge is a Request to curl cli transformer, which sounds like an interesting thing. maybe @sagikazarmark knows if it already exists?

**Comment by sagikazarmark** [comment]
We have this in [Ivory Http Adapter](https://github.com/egeloen/ivory-http-adapter/blob/master/doc/events.md#logger), definitely planned to be migrated.

**Comment by sagikazarmark** [comment]
See php-http/adapter#37

**Comment by ddeboer** [comment]
@dbu Let’s close this issue, as it properly belongs to the HTTP client we use, and php-http will have this.

**Comment by dbu** [comment]
agreed
