### ISSUE TITLE
Propose user hash shortcut for anonymous users

### ISSUE THREAD

**Issue by dbu** [FriendsOfSymfony/FOSHttpCache#132]
follow up of https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/pull/152/files#r19613053

ez does a clever trick in their varnish configuration to avoid a hash lookup for the anonymous users:
https://github.com/ezsystems/ezpublish-community/pull/198/files#diff-e135af71540ad18dca44b9b3949162baR142

varnish is probably even faster with restarting the request than the symfony cache, but it could still be beneficial for scenarios where many users are anonymous anyways.

this would just be something to add to the varnish configuration examples and explain in the user context documentation, no need to do anything on the php side.

**Comment by dbu** [comment]
why is that hash not simply "anonymous" to make it even more obvious?

**Comment by lolautruche** [comment]
Just for geek fun :-)

**Comment by ddeboer** [comment]
Please continue discussion in #182.
