### ISSUE TITLE
More general documentation

### ISSUE THREAD

**Issue by hpatoio** [FriendsOfSymfony/FOSHttpCache#144]
The documentation at the moment often refers directly and only to `Varnish` implementation. 

 - [x] http://foshttpcache.readthedocs.org/en/latest/testing-your-application.html
 - [x] http://foshttpcache.readthedocs.org/en/latest/contributing.html
 - etc.

Would be nice to have it more general with specific sections for each reverse proxy .

**Comment by dbu** [comment]
testing doc is now updated. anything else missing or shall we close this issue? we can always further improve when we stumble over other things.

**Comment by hpatoio** [comment]
It's ok to close this. As you said we can always open new issue.
