### ISSUE TITLE
Support basic auth in user context subscriber

### ISSUE THREAD

**Issue by dbu** [FriendsOfSymfony/FOSHttpCache#147]
The user context subscriber added in #145 should support basic authentication header instead or in addition to the session cookie.

The default behaviour should be to look at both authorization header and cookies, just as we propose with varnish. we could add an option to select one of the two exclusively and then ignore the other if the option is set.

**Comment by hpatoio** [comment]
The library call the the `URI` specified in `user_hash_uri` and there you generate the response content. See http://foshttpcache.readthedocs.org/en/latest/user-context.html#returning-the-user-context-hash

Am I right @dbu ?

**Comment by ddeboer** [comment]
That's exactly right, @hpatoio. See also http://foshttpcache.readthedocs.org/en/latest/symfony-cache-configuration.html.

**Comment by sprain** [comment]
Oh, I see. Thanks. I will look into it.

**Comment by ddeboer** [comment]
@sprain Great if you can add this functionality!

**Comment by dbu** [comment]
fixed in #167
