### ISSUE TITLE
Symfony HttpCache subscriber for custom proxy ttl

### ISSUE THREAD

**Issue by dbu** [FriendsOfSymfony/FOSHttpCache#151]
have a look at https://github.com/sulu-cmf/sulu/blob/develop/src/Sulu/Component/HttpCache/HttpCache.php and extract that into a subscriber, with the constant for the header as default value.

add new events to the HttpCache as needed in order to be able to do this.

**Comment by dbu** [comment]
this is only documented and used in FOSHttpCacheBundle, not in the library. i guess the kernel subscriber should thus also go to the bundle?

**Comment by dbu** [comment]
started working on it, see #214

**Comment by ddeboer** [comment]
:+1:

Agreed on having it in the library: everything which is not strictly (full-stack) Symfony should go here.
