### ISSUE TITLE
Standardise HTTP headers in Varnish config and docs

### ISSUE THREAD

**Issue by ddeboer** [FriendsOfSymfony/FOSHttpCache#157]
We should either consistently capitalise (`X-Cache-Debug`) or lowercase them (`x-cache-debug`). I suggest we follow the [default Varnish 4 VCL](https://www.varnish-cache.org/trac/browser/bin/varnishd/builtin.vcl) and capitalise.

**Comment by dbu** [comment]
+1 for capitalise. i think we do that for most things already.
