### ISSUE TITLE
For version 2: Drop all deprecated methods and cleanup doc

### ISSUE THREAD

**Issue by dbu** [FriendsOfSymfony/FOSHttpCache#163]

**Comment by ddeboer** [comment]
As far as I know, the `@deprecated` annotation only warns users whose IDE supports it or when they thoroughly look through our code (which they shouldn't have to do). Should we therefore also add `trigger_error()` at some stage? This, however, did cause major pain when Symfony added them.

**Comment by dbu** [comment]
i would only do the annotation and not bother with trigger_error. people who did not notice the deprecation will see fatal error which works for debugging too :-/

**Comment by ddeboer** [comment]
All right.

**Comment by ddeboer** [comment]
- [ ] convert to short array syntax
