### ISSUE TITLE
Symfony HttpCache Configuration error

### ISSUE THREAD

**Issue by borNfreee** [FriendsOfSymfony/FOSHttpCache#164]
Hi,

I try to integrate FOSHttpCache + FOSHttpCacheBundle and Symfony Reverse proxy.
There is an example of custom `AppCache` class on the [FOSHttpCache :: Symfony HttpCache Configuration](http://foshttpcache.readthedocs.org/en/latest/symfony-cache-configuration.html) page and there is a parent's constructor call with `$kernel` and `$cacheDir` parameters

This is not compatible with extended `Symfony\Component\HttpKernel\HttpCache\HttpCache`  class and it leads to fatal error.

Am i right?

In order to integrate Symfony project with FOSHttpCacheBundle, what class should be extended:
`FOS\HttpCache\SymfonyCache\EventDispatchingHttpCache`
or
`use FOS\HttpCacheBundle\SymfonyCache\EventDispatchingHttpCache`

I think documentation should be updated since it's not clear for developers.

**Comment by dbu** [comment]
if you use the bundle, you likely use symfony full stack and then you are better of with the class provided in the bundle as its extending the FrameworkBundle class and not just the one from the HttpKernel component.

when using the bundle, you should look at the bundle doc which is at:
http://foshttpcachebundle.readthedocs.org/en/latest/features/symfony-http-cache.html

keeping the two apart is tricky, there certainly is room for improvements. if you have suggestions where we should add a warning for bundle users in the component doc or how to clarify the bundle doc itself, please do.

**Comment by stof** [comment]
I suggest adding a warning in the library documentation saying that the bundle provides its own EventDispatchingHttpCache for integration in the fullstack framework

**Comment by dbu** [comment]
there was already a note. i promoted that to warning now.
