### ISSUE TITLE
Inconsistent default for context hash lookup url

### ISSUE THREAD

**Issue by dbu** [FriendsOfSymfony/FOSHttpCache#165]
The default URL for the user context hash lookup in varnish is [/user_context_hash.php](http://foshttpcache.readthedocs.org/en/latest/varnish-configuration.html#user-context) but for the symfony http cache subscriber it is [/_fos_user_context_hash](http://foshttpcache.readthedocs.org/en/latest/symfony-cache-configuration.html#user-context).

To make matters worse, the FOSHttpCacheBundle recommends [/user-context-hash](http://foshttpcachebundle.readthedocs.org/en/latest/reference/configuration/user-context.html#context-hash-route) as default route, being not very specific that the default varnish config is different. the symfony http cache instantiates the subscriber with default options, so its /_fos_user_context_hash.

I suggest that we change this to be the same everywhere. I like /user-context-hash best - the library backend hopefully does not consist of separate php files. there would be no BC break for the bundle configuration, and only a change in recommended configuration for the library when using varnish. it would be a BC break for the symfony httpcache subscriber however.

**Comment by ddeboer** [comment]
Lol, what a mess we made! :astonished: 

I agree with /user-context-hash. For the library keeping the PHP extension might be easier though, or we would have to configure Apache differently for the functional tests to pass.

**Comment by dbu** [comment]
we could do a folder user-context-hash with an index.php , no? is that clever or not really?

**Comment by ddeboer** [comment]
Let's try that!
