### ISSUE TITLE
What’s up with Scrutinizer code coverage?

### ISSUE THREAD

**Issue by ddeboer** [FriendsOfSymfony/FOSHttpCache#175]
It’s dropping like mad, but seems to be an issue with Scrutinizer itself: https://scrutinizer-ci.com/g/FriendsOfSymfony/FOSHttpCache/

**Comment by dbu** [comment]
when i run phpunit locally, i get an overall coverage of 93.17% so
scrutinizer seems to have a problem indeed. can you alert them?

**Comment by ddeboer** [comment]
https://github.com/scrutinizer-ci/scrutinizer/issues/312

**Comment by ddeboer** [comment]
Interestingly, our code coverage went up again to normal levels after the last commit. On Travis, the PHP builds [finished before](https://travis-ci.org/FriendsOfSymfony/FOSHttpCache/builds/54537018) the HHVM one, so Johannes’ explanation may be right.

**Comment by dbu** [comment]
so lets put a sleep 3 minutes to the travis build when its hhvm :-D

**Comment by ddeboer** [comment]
Yeah, that’s one solution. Probably better to reconfigure our Travis setup the way Johannes proposes. :wink:

**Comment by dbu** [comment]
oh, indeed, did not see that. can you do this?

**Comment by ddeboer** [comment]
Unfortunately, I haven’t found a correlation between the drop in coverage [in week 11](https://scrutinizer-ci.com/g/FriendsOfSymfony/FOSHttpCache/statistics/) and Travis build results from that time: the HHVM version hasn’t changed and there’s no clear difference in build results. Of course, it could be so that during one of the builds the HHVM task finished before any of the PHP ones, but I can’t tell from the results (runtimes don’t mean anything as tasks start at different times).

Anyway, as our  coverage continues to be reported as it should, I’ll leave this alone for now. If things change, we can always reopen this issue.
