### ISSUE TITLE
Warning during composer install/update about guzzle/http being abandonned

### ISSUE THREAD

**Issue by lolautruche** [FriendsOfSymfony/FOSHttpCache#176]
This seems quite recent.
Message is:

> Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
> Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
> Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
> Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.

How hard would it be to replace `guzzle/http` by `guzzle/guzzle`?

**Comment by ddeboer** [comment]
Not hard. :)

By the way, we’re getting rid of our hard dependency on Guzzle: #173 .

**Comment by stof** [comment]
this looks weird. guzzle/guzzle is the guzzle3 package, and they are providing subtree splits for it. Are they killing subtree splits without abandonnning the guzzle3 package ? Given that guzzle/guzzle is way bigger than guzzle/http, this would be weird.

**Comment by lolautruche** [comment]
Yep, I don't understand either...

**Comment by dbu** [comment]
the warning comes from packagist https://packagist.org/packages/guzzle/common . maybe they decided to stop maintaining the subtree splits...

i guess we need to discuss this with the maintainers of guzzle3.
