### ISSUE TITLE
Support UserContext Hash on openresty (nginx) 

### ISSUE THREAD

**Issue by joelwurtz** [FriendsOfSymfony/FOSHttpCache#184]
Hey,

After discussing with @lolautruche we think of the idea to support the user context hash on nginx by providing a lua script for [openresty](http://openresty.org/)

**Comment by dbu** [comment]
openresty sounds interesting. 

sounds like a doable idea. if there where simple plugins in nginx to do a web request and store the result in e.g. memcache or redis, we might get by with something even simpler.

@hpatoio any inputs on this idea?

**Comment by ddeboer** [comment]
Sounds cool!

**Comment by hpatoio** [comment]
I was thinking about using OpenResty/LUA to add advanced cache functionalities. I also did few tests with this library but it was all about configuring NGINX the right way. So I thought was not fitting in this project.

But I'm be happy to work on this. Would be nice to have a Vagrant Box to test stuff. I remember the environment setup was not trivial and a ready to use BOX can facilitate the adoption by other users.

**Comment by dbu** [comment]
if its too involved code on nginx side (needing to compile a custom nginx and similar issues) i think we indeed better just provide documentation explaining how to do things.

if somebody wants to work on this, now would be a good moment. we try to wrap up the 2.0 release in the next month or so, which is a window of opportunity for BC breaks if nginx would reveil that we need to generalize something that happened to be varnish specific.

**Comment by dbu** [comment]
i will close this as nothing happened. if somebody needs this and wants to build it, i am happy to discuss and either link to a separate repo or accept a pull request if its not too involved with extending nginx
