### ISSUE TITLE
[RFC] User context : Storing hash on user side and avoid the double request mecanism

### ISSUE THREAD

**Issue by joelwurtz** [FriendsOfSymfony/FOSHttpCache#185]
I think we can safely store the hash generated for the user context on the client side by generating a new format for it.

This idea is heavily inspired from the [JSON Web Token standard](http://jwt.io/).

The hash token, stored in a cookie, will be a string constituted of 2 parts : 

[hash].[signature]

* The [hash] will be the generated at the first connection and each time the context of the user change.
* For each new hash a [signature] will be generated given a private key

At each request, the reverse proxy will validate the hash by using a public key and the signature given, if it's valid the request will pass, if not it will return a bad request (400) / redirect to logout as the user may try to tampering this hash.

The implementation will be pretty straightforward for the Symfony reverse proxy, but much harder for varnish as we may need an external module to handle hash validation (like https://github.com/varnish/libvmod-digest)

**Comment by dbu** [comment]
after the first hash lookup, varnish and http cache will see the hash in their cache. so they kind of restart the request but only into their own cache.

i discussed at symfony live with people and we thought of another way to avoid this: use the varnish plugin for memcache or redis and store the hash value in there. we could also use the curl extension to simplify the hash lookup. with the Symfony HttpCache, any such thing is pretty straightforward.

i am rather afraid of exposing the hash to the client. if there is a way to reproduce a hash, a client could fake to be logged in. going with signing based on the current session is in the end just more complicated than just caching the hash in the caching proxy, i think. or do i miss some benefit here?

anyways, all of this should make no difference for the symfony application, so if we come up with good documentation, we can simply propose alternatives.

what i would really love to see first, however, is a performance test that can be used to compare the different approaches.

**Comment by dbu** [comment]
do we keep this open or should we close it? the title is misleading as storing the hash at the client seems not a valid option to me. other options could be, but would need a performance test setup or we are walking blindly.

i have no intention personally to work on this anytime soon.

**Comment by ddeboer** [comment]
Okay, closing this for now. @joelwurtz Please feel free to re-open this issue if you have new ideas.
