### ISSUE TITLE
Cache invalidation and user context

### ISSUE THREAD

**Issue by mpclarkson** [FriendsOfSymfony/FOSHttpCache#186]
Hi there

Does invalidating an entire route (e.g. /api/v1/projects) invalidate the cache for that route for each user when caching by user context using the Authorisation header?

Cheers :)
Matt

**Comment by dbu** [comment]
i wanted to point you to the documentation but realized we only talk about that in the phpdoc comment, but not the documentation. see #186 for an explanation. the short answer: purge works, refresh won't work. ban will work unless you add criteria to limit to only some of the vary headers when banning.

**Comment by mpclarkson** [comment]
cheers. I did look through the documents before posting. appreciated the quick response.
