### ISSUE TITLE
[RFC] Access to the responses of refresh requests

### ISSUE THREAD

**Issue by patkar** [FriendsOfSymfony/FOSHttpCache#188]
Since refresh are like normal requests but with a forced cache miss, it would be nice if we can access the responses (headers) in an event subscriber or such, when issuing a flush.

Use case would be for example logging the TTL and Age headers for future refreshes.

**Comment by dbu** [comment]
I think you could just subscribe to the guzzle client events... If there is an important use case, we can also provide something more. But i have problems understanding why you would need the response. TTL and Age are used by the caching proxy, not the application. The content will automatically expire once TTL is over. The refresh is for manual cache invalidation when you know that the content changed and you want the cache to update immediately. Can you explain more precisely what your use case is?

**Comment by patkar** [comment]
The backend application (shopware) is so slow, we must refresh all entries manually with a job queue when it expires, so the client doesn't experience slow response times randomly :(

And when we issue the refresh it TTL/Age from the response is saved to the db, for calculating the next manual refresh in the job queue. Ugly, but I can't change it.

**Comment by dbu** [comment]
oh wow, i see. so you trigger an automatic refresh when the page is about to get outdated again :-/
so you have your VCL add the TTL and Age to the response so that you would have that information?

does a guzzle event handler (like the one we do for the logs) be enough or does that not work? i think the event would be request.success from Guzzle\Http\Message\Request::getAllEvents - the event will contain both the request and the response, so it would be possible to determine whether this was a refresh or something else, if you use both.

**Comment by patkar** [comment]
Yes, after a long day building the warmup stuff, the event works. In the vcl the Age and TTL is added to the response, indeed. A little bit tricky, because I have to add a X-Url-Id header to the request, do identify the record in the urls table later in the event, but it work, yaaayyyy ^-^

**Comment by dbu** [comment]
great that it worked out. ping me on [twitter](https://twitter.com/dbu)
if you blog about your solution.

we might also start a sort of "cookbook" section in the documentation
for such scenarios, if you are interested in documenting how it works.

**Comment by ddeboer** [comment]
@patkar Cool that you were able to solve this.

Varnish 4 is able to fetch content in a background process, so clients won’t have to wait for it. Have you seen [grace mode](https://www.varnish-cache.org/docs/4.0/users-guide/vcl-grace.html?highlight=stale%20content#grace-mode) in the Varnish docs?

**Comment by hpatoio** [comment]
@patkar write a cookbook would be very nice ! If you need whatever kind of support just ask
