### ISSUE TITLE
[RFC] Support for guzzlehttp/guzzle?

### ISSUE THREAD

**Issue by patkar** [FriendsOfSymfony/FOSHttpCache#189]
FOSHttpCache uses the old `guzzle/guzzle` package, which is deprecated and will be abandoned in late 2015. Is there any plan to change to the `guzzlehttp/guzzle` package?

**Comment by ddeboer** [comment]
In fact, for version 2.0 of this package, we will migrate to an HTTP client abstraction layer (see #173). Users can then decide for themselves which HTTP client (such as Guzzle 5) they want to use. 

We prefer to wait with 2.0 until PSR-7 is final, but releasing before Guzzle 3 is abandoned becomes important then, too. Where did you find Guzzle 3 will be abandoned?

**Comment by patkar** [comment]
In the latest readme on https://github.com/guzzle/guzzle3

> Guzzle 3 is only maintained for bug and security fixes. Guzzle 3 will be EOL at some point in late 2015.

**Comment by ddeboer** [comment]
Thanks, @patkar. Now PSR-7 has been finalised, we’ll shortly be adding Guzzle 6 support through the HTTP adapter (#173).
