### ISSUE TITLE
Symfony HttpCache trait instead of class

### ISSUE THREAD

**Issue by dbu** [FriendsOfSymfony/FOSHttpCache#191]
When we stop php 5.3 support, we should convert the EventDispatchingHttpCache into a trait to reuse the logic with the FOSHttpCacheBundle kernel which extends a different HttpCache class and thus currently needs to copy the methods.

**Comment by ddeboer** [comment]
:+1:

**Comment by ddeboer** [comment]
We may want to restructure our abstract test case into one or more traits, too.

**Comment by ddeboer** [comment]
For the tests, see #218.

**Comment by dbu** [comment]
would traits actually help much? we need to extend methods of the HttpCache class. can a trait do that or does the user of the trait need to then tell which method wins?

**Comment by ddeboer** [comment]
As you can see in #233, overriding the methods is possible through the trait.
