### ISSUE TITLE
Symfony HttpCache invalidation client

### ISSUE THREAD

**Issue by ddeboer** [FriendsOfSymfony/FOSHttpCache#192]
See https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/pull/209#issuecomment-100185710. The client probably shouldn’t extend AbstractProxyClient, as it won’t be a HTTP client.

**Comment by dbu** [comment]
are you sure it is no HTTP client? it seems to me that the HttpCache instance is not provided as a service. or am i wrong here?

**Comment by ddeboer** [comment]
Ah, indeed, it needs to be as purging is currently done in Symfony HttpCache. I was just thinking: if we could have access to the [StoreInterface](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/HttpKernel/HttpCache/StoreInterface.php#L54), we might be able to invalidate requests from it directly (by a method call) instead of an HTTP request.

**Comment by dbu** [comment]
i have no idea if this is available as service, or if there are any plans to make it available. i will implement a http based client for now.

**Comment by ddeboer** [comment]
Agreed!

**Comment by dbu** [comment]
oh, anyways if you have more than one web server running HttpCache, you must go through HTTP. although if you have several servers, you really should be using Varnish or Nginx...
