### ISSUE TITLE
Add test for user context caching for different groups of anonymous users

### ISSUE THREAD

**Issue by ddeboer** [FriendsOfSymfony/FOSHttpCache#198]
E.g. based on a session value, say, view = A, B or C for 3 different representations of the same resource. 

Would the Symfony Cache UserContextSubscriber consider this anonymous requests or not? Do we already support this properly?

**Comment by dbu** [comment]
as soon as there is a session, the subscriber considers the request as not anonymous: https://github.com/FriendsOfSymfony/FOSHttpCache/blob/master/src/SymfonyCache/UserContextSubscriber.php#L197-L198

maybe we need to clarify the doc, i was also asked by somebody else about this. in terms of PHP, as soon as you have a session cookie, you are not anonymous anymore. in terms of symfony, [as soon as you access the session object, the session is created](http://symfony.com/doc/current/cookbook/session/avoid_session_start.html). if you are not be authenticated, you have the role `IS_AUTHENTICATED_ANONYMOUSLY` - but there is still a session so varnish/symfony cache will consider this as not anonymous. the symfony HttpCache knows nothing about security or so, it can't tell whats in a users session.

**Comment by ddeboer** [comment]
Agreed, this just requires some clarification in our docs.

**Comment by dbu** [comment]
we added some tests for this in https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/pull/576 and https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/pull/577
