### ISSUE TITLE
Create a Gitter room

### ISSUE THREAD

**Issue by ddeboer** [FriendsOfSymfony/FOSHttpCache#203]
I sometimes get questions from people on how to use the lib/bundle. We could create a Gitter room for first aid. The idea is that people can help each other there, and hopefully also gain some traction for FOSHttpCache. After all, configuring your HTTP cache right isn't the easiest thing for most user. We may also get some ideas about new features and maybe bugs that we need to solve.

@dbu Do you think this is manageable or do you prefer to just use the conventional channels (issues, e-mail, Twitter) instead?

**Comment by dbu** [comment]
i am not on gitter, and don't think i have much time for real-time
support. github issues, twitter and stackoverflow seem like a lot of
options to get support.

if gitter can send me email notifications for unanswered questions, i
would be ok to offer such a channel and see if it helps. having a dead
channel is worse than not having it at all, imho.

**Comment by dbu** [comment]
what shall we do about this?

**Comment by ddeboer** [comment]
I’ll just close this for now. We can always look into this later if the need arises.
