### ISSUE TITLE
Replace references to RFC 2616 with references to newer RFCs

### ISSUE THREAD

**Issue by ddeboer** [FriendsOfSymfony/FOSHttpCache#207]

**Comment by dbu** [comment]
you mean like i did in the bundle: https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/pull/207/files#diff-d04bcba83a2c4db056b82995f1c24b6bR178 ?

**Comment by ddeboer** [comment]
Exactly. Saw that and it’s a good idea.

**Comment by dbu** [comment]
hm, i searched the whole codebase and doc and found no single mention of neither rfc nor 2616. am i missing something or can we close this?

**Comment by ddeboer** [comment]
Good point, let’s close this.
