### ISSUE TITLE
Move autoloading to require-dev

### ISSUE THREAD

**Issue by ddeboer** [FriendsOfSymfony/FOSHttpCache#209]
I think we can move `"FOS\\HttpCache\\Tests\\": "tests/"` to `require-dev`, which will be a slight performance for users of the lib.

Needs check that all re-usable test case classes are in src/Test.

**Comment by dbu** [comment]
i am pretty sure they are, and as we told git to remove tests/ from the
distributed zip anyways, we would have a problem already.

so +1 for this change.
