### ISSUE TITLE
Tests don’t run on PHPUnit 3.7.*

### ISSUE THREAD

**Issue by ddeboer** [FriendsOfSymfony/FOSHttpCache#222]
Should we care about this?

**Comment by dbu** [comment]
imho no. can we specify the minimal phpunit requirement in
phpunit.xml.dist somehow?

**Comment by stof** [comment]
@ddeboer we don't IMO. PHPUnit 3.7 is years old and not supported anymore

**Comment by ddeboer** [comment]
@dbu I don’t think so; we can only specify a [minimum PHP version](https://phpunit.de/manual/current/en/appendixes.configuration.html).

Agreed, let’s close this.

**Comment by ddeboer** [comment]
Added a note to the docs: 2142008c270ed829d445499e5aa438b2f90eb46a.
