### ISSUE TITLE
Division into packages

### ISSUE THREAD

**Issue by ddeboer** [FriendsOfSymfony/FOSHttpCache#223]
Does it make sense to separate the library into more packages, moving it to a separate organisation?

* [httpcache](https://github.com/httpcache)/httpcache: current FOSHttpCache
* httpcache/httpcache-bundle: current FOSHttpCacheBundle
* httpcache/nginx: Nginx proxy client & tests
* httpcache/varnish: Varnish proxy client & tests
* httpcache/symfony-cache: Symfony HttpCache proxy client & tests
* httpcache/silex-provider: Silex integration 
* httpcache/test (the current test/ dir, which should have phpunit as a dependency): the re-usable test classes, such as the assertions and web server listeners.

**Comment by stof** [comment]
Can you describe what you would put in each package ?

**Comment by ddeboer** [comment]
Edited my original post to add those descriptions.

**Comment by stof** [comment]
``current FOSHttpCache`` looks weird as description though, as many other repos are getting code from it. the question is what is left in this repo. I'm not sure ``httpcache`` is the best name then

**Comment by ddeboer** [comment]
http-cache: interfaces and abstract classes

**Comment by ddeboer** [comment]
By the way, @stof: this is just an architecture/organisation question. I really do appreciate all your help and comments on our FOS repos!

**Comment by stof** [comment]
There is a question if it moves to a different organization though: would it stay in the ``FOS`` namespace ?

**Comment by ddeboer** [comment]
It would move to a different namespace then too, so we should include in our discussion whether that’s a desired outcome or not.

**Comment by dbu** [comment]
i propose that we leave this for now (so version 2 would still be all in one repository). is that okay? we could label the issue "on hold"...

**Comment by ddeboer** [comment]
That’s fine with me. Putting this on hold.
