### ISSUE TITLE
error: assignment discards ‘const’ qualifier from pointer target type

### ISSUE THREAD

**Issue by skonsoft** [FriendsOfSymfony/FOSHttpCache#247]
After adding the fos_custom_ttl_backend_response to vcl_response, i get this error:

```
oct. 31 15:05:43 pc-venitron varnishd[14291]: Message from C-compiler:
oct. 31 15:05:43 pc-venitron varnishd[14291]: vgc.c: In function ‘VGC_function_fos_custom_ttl_backend_response’:
oct. 31 15:05:43 pc-venitron varnishd[14291]: vgc.c:3368:17: error: assignment discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
oct. 31 15:05:43 pc-venitron varnishd[14291]: ttl = VRT_GetHdr(ctx, &hdr);
oct. 31 15:05:43 pc-venitron varnishd[14291]: ^
oct. 31 15:05:43 pc-venitron varnishd[14291]: cc1: all warnings being treated as errors
oct. 31 15:05:43 pc-venitron varnishd[14291]: Running C-compiler failed, exited with 1
```

I followed the doc install but it fails due this error.

I'm using ubuntu 15.10 and varnish-4.1.0 revision 3041728

As in doc said, i had enabled the C inline to use this feature  by setting this config in varnish.service (The new systemd tool in ubuntu 15.10). Here is the config:

```
[Unit]
Description=Varnish Cache, a high-performance HTTP accelerator

[Service]
Type=forking
LimitNOFILE=131072
LimitMEMLOCK=82000
ExecStartPre=/usr/sbin/varnishd -C -f /etc/varnish/default.vcl -p vcc_allow_inline_c=on
ExecStart=/usr/sbin/varnishd -a :80 -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,512m -p vcc_allow_inline_c=on
ExecReload=/usr/share/varnish/reload-vcl

[Install]
WantedBy=multi-user.target
```

Any Help ?

Thank you

**Comment by skonsoft** [comment]
After making some changes, i added a const keyword to ttl variable and it works. I don't know if this the right way to do it or not .

old config:

```C
C{
            char *ttl;
            const struct gethdr_s hdr = { HDR_BERESP, "\024X-Reverse-Proxy-TTL:" };
            ttl = VRT_GetHdr(ctx, &hdr);
            VRT_l_beresp_ttl(ctx, atoi(ttl));
        }C
````
New config:
```C
C{
            const char *ttl;
            const struct gethdr_s hdr = { HDR_BERESP, "\024X-Reverse-Proxy-TTL:" };
            ttl = VRT_GetHdr(ctx, &hdr);
            VRT_l_beresp_ttl(ctx, atoi(ttl));
        }C
````

Please any help  ?

Thank you

**Comment by dbu** [comment]
hi @skonsoft , what version of varnish do you use? the documentation provides different code fragments for varnish 3 and 4. can you please make sure you are trying with the correct one? if you do and have a very new varnish 4, there might be some BC break or something going on in varnish and we need another option to support new varnish 4 versions... but lets first make sure this really is the problem.

**Comment by skonsoft** [comment]
Hi,
@dbu I use varnish 4.1. It's the newest one with ubuntu server 15.10.

**Comment by dbu** [comment]
okay. we seem to use 4.0 on travis-ci. i don't see if there is a warning output when varnish is compiled. i suspect that normally, warnings do not lead to not compiling, but your system is somehow configured to abort on warnings. anyways, i just created #248 to see if things work with 4.0 as well. if they do we merge that.

**Comment by dbu** [comment]
okay, that seems to work. thanks for reporting and proposing the fix.
