### ISSUE TITLE
Use StyleCI?

### ISSUE THREAD

**Issue by dantleech** [FriendsOfSymfony/FOSHttpCache#263]
[Style CI](http://styleci.io) is a continuous integeration service for coding style based on phpcsfixer. It the build "fails" then it provides a patch which can be applied to fix it.

It also maintains the class doc headers.

**Comment by dbu** [comment]
:+1:

**Comment by stof** [comment]
:+1:

**Comment by ddeboer** [comment]
What benefit does Style CI have over running code inspection on Scrutinizer?

**Comment by dantleech** [comment]
Style CI is only about style (not sure if Scrutinizer picks up CS
violations) and it allows you to download a patch containing the
necessary fixes (or make a PR IIRC).

**Comment by dbu** [comment]
done in #293
