### ISSUE TITLE
Out of band tag handling

### ISSUE THREAD

**Issue by dbu** [FriendsOfSymfony/FOSHttpCache#265]
the current tag handling is all about sending tags with the response and sending tag specific requests to the caching proxy. there is another concept for tagging: storing tag => urls ourselves (database, sqlite, redis, whatever) and send normal refresh / ban requests on invalidation. (see also the symfony con talk by @magnusnordlander)

how can we model this set up? should we add an `isInline` check to TagsInterface and a `saveTags($requestUrl)` in ResponseTagger? maybe rather have an InlineTagsInterface for the get header name and get header value methods?
or should we try to hide this away and magically save tags in ResponseTagger on getTagsHeaderValue?

the TagsInterface::invalidateTags looks fine to me. but the clients (Varnish/Nginx/Symfony) should maybe use composition for the functionality rather than implement the method inline, so you can plug either one that calls ban() on the client or the one that calls purge / refresh based on its stored tag to url map.

**Comment by ddeboer** [comment]
Ping @dantleech, who has already been thinking about (and drawing) this.

**Comment by dantleech** [comment]
#253 adds a tag `ManagerInterface` (extending a (tag) `InvalidatorInterface`) which takes care of invalidating and associating tags with "cache IDs" (could be URL or content digest, or whatever). It also introduces `StorageInterface` which exists to actually persist these associations (currently a `DoctrineCache` implementation) - the `StorageInterface` would be used by `ManagerInterface` implementations as required.

The tag invalidator (`InvalidatorInterface` - which is extended by `ManagerInterface`) is currently passed to the proxy client as an option.

I think that the finished PR *should* provide the architecture for invalidating, but might still need some jiggling about.

**Comment by dbu** [comment]
there are two parts here: the library internal architecture how to
implement things in a flexible way. the other part is what/how to expose
this to the users of the library to make things not overly complicated.

**Comment by magnusnordlander** [comment]
If you guys want we can set up a Hangout and I can talk a little bit more about how we've implemented our tag manager.

**Comment by dbu** [comment]
hi magnus, thanks for the offer. that would be cool! i could make time
next week tuesday to friday during working hours (GMT +1 timezone, i
think norway is in the same zone)

**Comment by dantleech** [comment]
Anytime would be OK with me.

**Comment by magnusnordlander** [comment]
Shall we say Tuesday the 15th, at 14:00 GMT+1? (Also, I'm Swedish, not Norwegian :) )

**Comment by ddeboer** [comment]
Sounds good to me.

**Comment by dbu** [comment]
works for me. though i have the next meeting at 14:30 so we have a strict timebox. 13:30 would also be possible for me, if we want a bit more time. and sorry for the nationality blunder ;-)

my google identity is david@liip.ch . i can try to assemble people on tuesday. i have @ddeboer but i think i don't have @dantleech in google yet.

**Comment by dantleech** [comment]
I have never used google hangouts, but my identity would be `dan.t.leech@gmail.com`, will try and do that.

**Comment by dbu** [comment]
turns out my meeting was moved, so 14:00 is perfect and i have more time if needed (but lets try to keep this short). i created a gist with an idea how the new interface could look https://gist.github.com/dbu/5b162a6707d8922014c9

**Comment by dbu** [comment]
okay, i am trying to call you guys on hangout.

**Comment by magnusnordlander** [comment]
Hangout is up at https://hangouts.google.com/hangouts/_/nordlander.se/cachetags

**Comment by dbu** [comment]
ah :-)

**Comment by dantleech** [comment]
Thanks for the chat. What I took away from this is that we should be transactional when handling the tags, otherwise I *think* we are broadly on the same track with https://github.com/FriendsOfSymfony/FOSHttpCache/pull/253

@magnusnordlander is your code available publically?

**Comment by dbu** [comment]
thanks again for the input. essential take-aways:

* apart from the OO integration, the solution from magnus looks very similar to where we are heading
   * CacheManager to invalidate tags
   * TagStore to save tags for a specific URL (with symfony integration using the RequestStack to not need explicit request object)
* TagStore is transactional (our implementation is basically as well: you add tags to the TagHandler and only "flush" them at the end right before the response is sent to the client)
* normalize the request URL => actually why @magnusnordlander ? if akamai cached ?a=b&c=d and ?c=d&a=b, we need to purge both of those, no?

**Comment by dbu** [comment]
@dantleech @ddeboer did you see the gist i created at https://gist.github.com/dbu/5b162a6707d8922014c9 ? i think this is how things should look actually. with that it would be totally transparent what kind of signaling is used.

in addition, we would keep "something" that you can store tags in, as we have now. for the out of band, we also need a tag storage thing much like magnus has. in the case of symfony cache, that storage thing can be shared between the HttpCache storing the tags on the response and the invalidation tool.

**Comment by magnusnordlander** [comment]
@dantleech No, it's a part of a proprietary application.

@dbu No, `http://www.example.com/?a=b&c=d` and `http://www.example.com/?c=d&a=b` refers to the same cache object, at least in our implementation, so purging one also purges the other. Same thing with `http://www.example.com/` and `http://www.example.com/?`.

**Comment by dbu** [comment]
is that an akamai feature? or does akamai forward tell you the cache object id when sending the request? caches like varnish treat the URL as an opaque string, they don't have any logic regarding the semantics of query parameters afaik

**Comment by magnusnordlander** [comment]
Technically, the cache key in Akamai is the ARL (Akamai Resource Locator). The conversion from URL to ARL is configurable, so you (or more likely your technical contact at Akamai) can change what goes in to the ARL. Whenever you send a purge request using a URL, that simply is converted to an ARL.

I believe query parameter normalization is a part of the default URL-to-ARL conversion, but I can't say for sure, since we're using a custom one.

**Comment by dbu** [comment]
okay, i see. so for use with nginx or varnish, we probably don't want to normalize the URLs. in the case of akamai, this is an optimization to not send duplicate invalidation requests for the same ARL.

@magnusnordlander once we have this thing going, would you be willing to share the akamai client code you have? or do they even provide an sdk?

**Comment by magnusnordlander** [comment]
In fact, for Akamai specifics, maybe @dshafik would be able to tell more?

Akamai has a part of an SDK for the authentication part of using their APIs (which coincidentally is the hard part). I'll need to check with my client first, but I'm fairly sure that can to contribute the code necessary to actually do the purging with Akamai. If not, it's not at all difficult once you have the authentication handled. Ping @sirowl.

**Comment by dshafik** [comment]
Thanks for pinging me @magnusnordlander; as you say purging is very simple. You can see a full example here: https://github.com/akamai-open/api-kickstart/blob/master/examples/php/ccu.php

You just need the appropriate credentials fed into `\Akamai\Open\Edgegrid\Client`, or if you're already using Guzzle I recommend simply registering the middleware as shown [here](https://github.com/akamai-open/AkamaiOPEN-edgegrid-php#authentication-handler)

Also, _by default_ we _**preserve**_ the order of query args; so it might be good to normalize them.

**Comment by sirowl** [comment]
@magnusnordlander I have no problem with us contributing in this regard.

**Comment by andrerom** [comment]
@dbu How will the architecture look like? Assuming Varnish does support softban in the future we should allow for cache backends (*invalidators*) to handle tagging themselves or?

If so db based tag backend can for instance decorate cache backends to take care of tags and refresh/purge/expire associated urls on the actual backend.

**Comment by dbu** [comment]
i want to refactor the tagging in a way that supports both scenarios. i think the invalidation part is already quite ok since the refactoring: we call a method telling we want to invalidate some tag. this might delete a cache file or send some http request(s) (BAN or PURGE or REFRESH, or it could talk to akamai in some way). 

for the recording side, its a bit more tricky: either we need to record information in the response (which might be symfony response, psr7 response, or something we don't know so the user needs to get the tag header value and set it themselves) or we need to store the tag to request url map somehow. the url is simple to determine in symfony with the RequestStack, but in the generic case we would need that passed in (we could look at $_SERVER as a fallback?). i am not sure how to press those two scenarios into a concise tag handler class without making it utterly confusing for the user. not sure if we should be rather implicit and e.g. store the tag to url map when requesting the tags, or provide two explicitly different handlers and tell the user to use one or the other (and in the symfony listener check which kind of tag handler we have)

**Comment by dbu** [comment]
another example of an external cache tagging system would be [fastly](https://docs.fastly.com/guides/purging/setting-surrogate-key-headers-based-on-a-url)

**Comment by dantleech** [comment]
bump .. how can we move forward on this?

Is there anything wrong with this [PR](https://github.com/FriendsOfSymfony/FOSHttpCache/pull/253) (other than its WIP status)?

I previously missed the gist that @dbu posted earlier in this thread, but as far as I can tell we need not support the `Request` object(s) in the "TagManagerInterface", instead the "TagManager" impl. (i.e. the Symfony proxy) could be called by a subscriber, which would take care of accepting and getting the information from the request.

As [in the PR](https://github.com/FriendsOfSymfony/FOSHttpCache/pull/253/files#diff-98b1c2253534811a3defe886db356690R54) the invalidate method could simply be:

```php
public function invalidateTags(array $tags, $cacheId, $lifetime);
```

**Comment by dbu** [comment]
i wonder if we could change #253 to be a generic out of band tag handling solution? it would store the tags to thing to invalidate maps and have handlers to send invalidation requests.

i still think that gist does make sense: for invalidating, we just specify the tags when calling the top level invalidateTags method. the out of band system could use another abstraction to actually talk to the caching api for the invalidation. for tagging i just commented on the gist: the user code should not need to care whether its inband or out of band, so we should always pass the request to the method.

**Comment by dantleech** [comment]
That PR has a cache storage interface with the method `tagCacheId(array $tags, $identifier, $lifetime)`. The `$identifier` could be a content-hash (for the Symfony implementation) or a URL. Is there anything missing?

**Comment by dbu** [comment]
@dantleech sorry, i won't manage to wrap this / #253 up before i leave for holidays tomorrow. 

the whole size of the PR and discussion makes me wonder if we should remove everything tag from FOSHttpCache and have a dedicated FOSHttpCacheTag for this functionality. it seems all in all we need many components, which is warping FOSHttpCache that has many other functionalities besides cache tagging.
not sure if that would mean that we also would need a FOSHttpCacheTagBundle or if the bundle can reunion the two things, because the symfony integration would be much smaller.

**Comment by andrerom** [comment]
Could make sense, as mentioned above have been thinking there is a need for a small tagging service that uses dbal that can be used here with adapter, and used by tagging enhanced PSR-6 cache service. So would be simpler if we break the problems into smaller pieces.

**Comment by dantleech** [comment]
What do you think about a dedicated package for Symfony HttpCache tagging rather than trying to generalize it? Such a package would be unaware of this package, and then maybe this component could integrate with it.

**Comment by dbu** [comment]
that could be another option, yes. the complexity of the Symfony
HttpCache is certainly the highest complexity.

another option could be to not try to integrate that deep with HttpCache
and simply store the tag to url map as we will do for varnish and send
invalidation requests, letting HttpCache look up those urls. that would
be a lot simpler, though less efficient. but then, HttpCache is not the
high end solution anyways so if efficiency matters one might need to use
varnish or nginx anyways.

**Comment by dbu** [comment]
the code has been refactored in a way that should allow out of band handling. there is TagHandler to record tag information and do http header translation if wanted, and ResponseTagger for working with PSR-7 in-band tagging. FOSHttpCacheBundle will be refactored accordingly.
