### ISSUE TITLE
Suggestion : do not always add user hash Vary header in UserContextSubscriber listener

### ISSUE THREAD

**Issue by supasteev0** [FriendsOfSymfony/FOSHttpCache#277]
I noticed the "X-User-Context-Hash" (or X-User-Hash in ez publish app) is always added to the Vary header whenever the "X-User-Context-Hash" header exists in the request.

As a consequence, all responses get the User Hash in Vary header, and therefore generate different cached versions in Varnish. 

But, even on a website managing frontend user connection, we do not always want the cache to vary on the user hash, as we want to decide which pages/ESI need to really vary depending on this criterion (and we therefore set the User Hash Vary header ourselves in the corresponding controller action).

Would it not be a good idea to let the symfony app controllers manage the Vary header instead of doing it automatically for all responses in the fosHttpCache Bundle UserContextSubscriber listener ?

**Comment by ballinette** [comment]
:+1:

**Comment by dbu** [comment]
the [current stable code](https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/1.3/EventListener/UserContextSubscriber.php#L120-L142) as well as master does not add the Vary if there was no hash header in the request.

by default, we need to send the vary header. people usually don't read the complete documentation, and could shoot themselves in the foot and mix up caches, which is a far more severe problem than duplicated caches.
assume i request the page as authenticated user, its cached without varying on the context, and then an anonymous user requests the same page. he would have a different hash, but as the response did not vary on the hash, he gets the logged in page view...

what would make a lot of sense however is to have an option on the user context configuration to disable setting the vary header automatically. something like `always_vary_on_context_hash` default: true. the documentation would explain that you can set this to false if you want to set up your own rules for when to cache. with a big fat warning that you have to be careful with this to not expose protected content. would that help you? do you want to do a PR against master for this feature?

**Comment by supasteev0** [comment]
Hello David, 

Having an option in the configuration to set the Vary header automatically or not is a very good idea.
We will make a PR in the next few days.

Thanks

**Comment by dbu** [comment]
fixed in https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/pull/288
