### ISSUE TITLE
remove x- from our headers

### ISSUE THREAD

**Issue by dbu** [FriendsOfSymfony/FOSHttpCache#279]
[rfc6648](http://tools.ietf.org/html/rfc6648) says to not prefix headers with x- but if anything use a vendor prefix. lets change everything to fos- instead of x-

**Comment by ddeboer** [comment]
However, that RFC also [states](http://tools.ietf.org/html/rfc6648#section-3) that new header creators ‘SHOULD NOT prefix their parameter names with "X-" or similar constructs’. I guess `fos-` would be a similar construct. The idea seems to be that we should assume that any of our headers could become general in principle. So perhaps get rid of the prefix altogether?

**Comment by dbu** [comment]
you are right. these are just the default names, so if somebody indeed
does run into a naming conflict, they can simply change the defaults we
provide. lets do that then.

**Comment by dbu** [comment]
see discussion in #285 - we will keep the prefix to avoid an unnecessary upgrading gotcha.
