### ISSUE TITLE
[RFC] Avoid double request with user context by providing a signed hash 

### ISSUE THREAD

**Issue by joelwurtz** [FriendsOfSymfony/FOSHttpCache#282]
This is something that i have mind for a long time, inspired from the Json Web Token specification.

The purpose is to have the PHP application generating a user context hash and a signature by using a private key when it's not present, with maybe something like this : Hash|Signature (or using json like JWT, or whatever, don't really know the best thing here)

This hash can then be set in a Cookie (for easier persistence) or in a specific header (harder to use on browser side, more for API).

On subsequent request the hash is read by the reverse proxy and validated using a public key. If hash is present and valid then it's used to fetch the cache in the reverse proxy, if not, no cache is provided.

Good points : 

 * No more user context hash request, and restart "hack"
 * Simpler workflow

Bad points : 

 * Header is anonymous (someone can just give this header to another people which will profit from the cache), but we can mitigate that by adding user information in the header so it will be different for every person, but hash in this header will be the same for each context.
 * Need a VMOD on varnish

WDYT ?

**Comment by dbu** [comment]
i am sceptical if this is a good idea. if i understand correctly, the first request would then never come from the cache but has to go to the backend to generate the right cookie. and for api clients, this would need special consideration on client side, whereas the current implementation is transparent for the client.

if you want to use non-standard vmod, you can also do the hash lookup with a curl request and use memcache/redis to store session/auth to hash map. this will be less hacky than the restart, and likely more efficient.
