### ISSUE TITLE
make it easier to troubleshoot error-400 responses

### ISSUE THREAD

**Issue by gggeek** [FriendsOfSymfony/FOSHttpCache#284]
In UserContextSubscriber, if the user-hash header is missing, an error 400 will be returned to the user:
- with no indication of the root of the problem to the user
- with no indication in the logs, either

It would be nice if this was easier to troubleshoot

**Comment by gggeek** [comment]
As a side note: a single line in the apache config can be used to trigger the usage of httpcache in a  context where there is a reverse proxy in front, and the error 400 to appear

**Comment by dbu** [comment]
i agree that good error responses are an important time safer for developers. glad if we can improve something.

are you talking about https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/master/EventListener/UserContextSubscriber.php (in the bundle repository, not this one)? i don't see where we would trigger the error 400. glad if you can do a pull request with a simple solution (maybe simply have a description on the exception so that its logged / shown in debug mode?)

**Comment by gggeek** [comment]
I think that it is in https://github.com/FriendsOfSymfony/FOSHttpCache/blob/8019bad9b3c1746263c5d83df844914983fa8fae/src/SymfonyCache/UserContextSubscriber.php, line 102.

Will try to find the tome to think about a good message which compromises between information and security

**Comment by dbu** [comment]
ah, i see. right, lets add something there. glad if you can do a pull
request. i think as long as its a static message and not using anything
from the request it should be ok.
can this happen in other situations than when custom development on the
AppCache or an extended event subscriber class lead to some mismatch?

**Comment by gggeek** [comment]
a million dollar question... :-)

**Comment by dbu** [comment]
ping @gggeek

**Comment by dbu** [comment]
@gggeek i aim to release 2.0 in september. it would be great if you find time to come up with an idea here. now we still can do BC breaks if needed. once we have a beta release, we won't do BC breaks anymore for non-critical issues.

**Comment by gggeek** [comment]
@dbu I ll try to give it a look over the weekend...

**Comment by dbu** [comment]
i will close this issue for now. but if you find time to look into this and provide an improvement PR, please do @gggeek . the release did not happen but i am about to finish the rewriting of the HTTP layer to use HTTPlug.
