### ISSUE TITLE
support symfony reverse proxy cache tagging

### ISSUE THREAD

**Issue by dbu** [FriendsOfSymfony/FOSHttpCache#288]
symfony 3.2 will have tagged caching on the reverse proxy. we should check out already how we can support this so we are ready when symfony 3.2 comes out.

see https://github.com/symfony/symfony/pull/19047 for the code changes on symfony side.

**Comment by erichard** [comment]
I don't see how the tagged caching will be used in the reverse proxy. AFAIK it does not make use of the Cache component.

Did I miss something ?

**Comment by dbu** [comment]
it looks like @nicolas-grekas did the PR without a matching doc PR (at least nothing is linked in https://github.com/symfony/symfony/pull/19047)  . 

indeed it seems that i misread that PR, its not about the reverse proxy but only about the caching component. and the HttpCache indeed does not use the caching component but implement its own file system based caching if i read correctly (abstracted with a StoreInterface that does not offer cache tagging functionality). i will comment on #286 and close this issue.
