### ISSUE TITLE
guzzle/guzzle is abandoned -> use guzzlehttp/guzzle instead

### ISSUE THREAD

**Issue by mvhirsch** [FriendsOfSymfony/FOSHttpCache#299]
The package *guzzle/guzzle* is abandoned and will not longer be maintained. Instead we should use *guzzlehttp/guzzle* here, but this requires upgrading to at least v4 (which is also EOL).

I would rather suggest, rebuilding the `AbstractProxyClient` (and everything else depending on guzzle) with the current version 6.

**Comment by mvhirsch** [comment]
Ah I see, depending on package *guzzle/guzzle* was already removed in *master* 6a3f996f4

Looking forward a new release of this package :+1:

**Comment by dbu** [comment]
> Ah I see, depending on package /guzzle/guzzle/ was already removed in
> /master/ 6a3f996
> <https://github.com/FriendsOfSymfony/FOSHttpCache/commit/6a3f996f43cdddabd60b4dc02541e49748f2aa09>
> 
> Looking forward a new release of this package

yeah, we switched to use the php-http/httplug abstraction to not tie
ourselves to a specific client implementation. there are a bunch of open
issues before we can release 2.0 - i hope we get to wrap them up soonish.
if you have time to check master out and provide feedback, that would be
appreciated. (but i would not switch your project to master yet, there
might still be some BC breaks)
