### ISSUE TITLE
1.x release with newer version of Guzzle?

### ISSUE THREAD

**Issue by andrerom** [FriendsOfSymfony/FOSHttpCache#309]
Guzzle 3 is as of this commit incompatible with Symfony 3: https://github.com/guzzle/guzzle3/commit/9d45318ad04893dbe491c5a682353ea24f3178eb

Meaning on Symfony 3 you'll get Guzzle 3.8.1.

What about small update to use Guzzle 5|6 to support all relevant php versions supported by 1.x?
*(given master is intended for 2.0)*

**Comment by dbu** [comment]
ah damn. how small would that update be for using guzzle 3? it would be a BC break when explicitly instantiating the guzzle client and injecting it to our proxy client.

i would much rather release 2.0 with HTTPlug soon. i will be on holidays and web summer camp next week and won't have time before that for anything. looking at the [milestone](https://github.com/FriendsOfSymfony/FOSHttpCache/milestone/4) there is #285 where i hope for input from users if the idea is good or bad, plus some cleanup that is not really even a blocker for 2.0.
and then the topic of out of band handling and tagging - which we could also postpone to get the release out.

if its a rather trivial change and you want to do a pull request, i am ok to merge it and do a version 1.5 with a warning about the BC break. 2.0 will still take at least a few weeks to get ready.

**Comment by andrerom** [comment]
Ok, I was under the impression 2.0 had stalled because of the tag implementation question, which by now could be solved by building on top of Symfony Cache Component *(as of 3.2 out in a few months)* and let that deal with it.

But if 2.0 is out soon then I'll rather close this, not worth the effort.
