### ISSUE TITLE
Drop Varnish 3 support for 2.0?

### ISSUE THREAD

**Issue by andrerom** [FriendsOfSymfony/FOSHttpCache#331]
With Varnish 4(.1) fully cable of running vmods, and having been out for 2,5 years, and available on all distros. I would assume we can drop Varnish 3 now.

Possible follow up:
- afaik current VCL for 4 should work on Varnish 5
- varnish-modules is starting to show up several places, Ubuntu 16.10 and Debian Stretch has it, if we have a second set of vcl it could be one using that (xkey).

**Comment by ddeboer** [comment]
> varnish-modules is starting to show up several places, Ubuntu 16.10 and Debian Stretch has it, if we have a second set of vcl it could be one using that (xkey).

Is that package [this list of modules](https://github.com/varnish/varnish-modules/tree/master/src)? Unfortunately not the curl vmod is not included: that one would be [useful for our context hash lookups](https://github.com/FriendsOfSymfony/FOSHttpCache/issues/182#issuecomment-255049087).

> afaik current VCL for 4 should work on Varnish 5

Correct: we recently [added Varnish 5 support](https://github.com/FriendsOfSymfony/FOSHttpCache/pull/322). Only a minimal change was needed: moving the invalidators section up. We decided to keep Varnish 3 support for now, as there’s not really a reason to drop it.

**Comment by andrerom** [comment]
> Is that package this list of modules? Unfortunately the curl vmod is not included: that one would be useful for our context hash lookups.

https://github.com/varnish/varnish-modules/issues/46

**Comment by andrerom** [comment]
> We decided to keep Varnish 3 support for now, as there’s not really a reason to drop it.

It's EOL since 2015, I assume we inted to keep pushing security patches to 1.x for a few years, sothat is the two reasons I proposed it. _(besides spending the surplus testing matrix on Varnish with xkey and potentially other confirgurations)_.
https://www.varnish-cache.org/lists/pipermail/varnish-misc/2015-April/024359.html

**Comment by ddeboer** [comment]
Yeah, I suggested [the same in a previous discussion](https://github.com/FriendsOfSymfony/FOSHttpCache/issues/319#issuecomment-256110573). On the one hand, I agree with @dbu that as of now there’s no binding reason to drop Varnish 3 support for our version 2.0. However, I fear that when we start adding features, the effort of maintaining them on Varnish 3 will become too high. Following semver, we would have to publish FOSHttpCache 3.0 if we wanted to drop Varnish 3 support later.

**Comment by andrerom** [comment]
> Following semver, we would have to publish FOSHttpCache 3.0 if we wanted to drop Varnish 3 support later.

yes, and that is perhaps a reason good enough to also bump php version to 5.6. _Twig 2.0 just did that this week._

**Comment by dbu** [comment]
our support for varnish 3 consists in providing vcl files for it. imo its not a BC break to stop updating those files and deprecating varnish 3 when we have a new feature that needs new vcl.

**Comment by ddeboer** [comment]
> our support for varnish 3 consists in providing vcl files for it. imo its not a BC break to stop updating those files and deprecating varnish 3 when we have a new feature that needs new vcl.

So let’s decide for now to keep Varnish 3 support (in FOSHttpCache 2.0) but not promise feature completeness on Varnish 3 (if the effort of maintaining the VCL’s becomes too high).
