### ISSUE TITLE
minimum-stability override usage for entire FOSHttpCache bundle for Varnish5 compat?

### ISSUE THREAD

**Issue by pgnd** [FriendsOfSymfony/FOSHttpCache#355]
I'm setting up a new symfony3.3 install behind a Varnish5 instance.

IIUC, here, I need http-cache-bundle >= v2

In my project, set (as usual) with
```
    "minimum-stability": "stable",
```
I set an @dev override
```
	vi composer.json
		...
		"require": {
		    ...
		+           "friendsofsymfony/http-cache-bundle": "2.0.*@dev",
		    ...
		}
		...
```
then
```
	composer require \
	 friendsofsymfony/http-cache-bundle:2.0.x-dev
```
That returns
```
	friendsofsymfony/http-cache-bundle:2.0.x-dev
	./composer.json has been updated
	Loading composer repositories with package information
	Updating dependencies (including require-dev)
	Your requirements could not be resolved to an installable set of packages.

	  Problem 1
	    - Installation request for friendsofsymfony/http-cache-bundle 2.0.x-dev -> satisfiable by friendsofsymfony/http-cache-bundle[2.0.x-dev].
	    - friendsofsymfony/http-cache-bundle 2.0.x-dev requires friendsofsymfony/http-cache ^2.0.0-beta3 -> satisfiable by friendsofsymfony/http-cache[2.0.0-beta3, 2.0.x-dev] but these conflict with your requirements or minimum-stability.
```
Is setting individual requires for the *bundle* components, e.g. friendsofsymfony/http-cache, necessary?

Or am I incorrectly spec'ing the require?

I.e., what do I need to config to grab 'all' of the friendsofsymfony/http-cache-bundle @dev stability, for (eventual) Varnish5 compat?

**Comment by pgnd** [comment]
It appears I need both
```
	edit composer.json
			...
			"require": {
			    ...
		+	           "friendsofsymfony/http-cache-bundle": "2.0.*@dev",
		+	           "friendsofsymfony/http-cache": "2.0.*@dev",
			    ...
			}
			...
```
now,
```
	composer require \
	 friendsofsymfony/http-cache:2.0.x-dev \
	 friendsofsymfony/http-cache-bundle:2.0.x-dev
```
execs with no error
```
	composer show | grep symfony/http
		friendsofsymfony/http-cache          dev-master bd0ce29 Tools to manage HTTP caching proxies with PHP
		friendsofsymfony/http-cache-bundle   dev-master 8dc0056 Set path based HTTP cache headers and send invalidation requests to your HTTP cache
```
and my basic site is up and is, at least, responding through Varnish 5
```
	varnishlog
		...
		-   RespHeader     Via: 1.1 varnish (Varnish/5.1)
		-   VCL_call       DELIVER
		-   RespHeader     X-Cache: HIT
		-   RespHeader     X-Cache-Hits: 1
		...
```
It'll still be useful to know if there's a correct method that specifies ONLY the bundle's stability.

**Comment by dbu** [comment]
this is the correct way, relaxing stability does not cascade to the dependencies of a dependency. if the library would be released as stable, specifying only the bundle would be enough, but as is both are only at beta. 

does the library and bundle work well for you? i hope to tag 2.0.0 stable this week, so feedback on the new version is highly appreciated. 

once the release is out, you can switch to a normal require of `^2.0.0` of the bundle and remove the line about the library again.

**Comment by pgnd** [comment]
> relaxing stability does not cascade to the dependencies of a dependency. if the library would be released as stable, specifying only the bundle would be enough, but as is both are only at beta.

got it.  thanks.

> does the library and bundle work well for you? i hope to tag 2.0.0 stable this week, so feedback on the new version is highly appreciated.

so far, so good.  *not* thoroughly tested yet, as the site's just building up.  but, I'm seeing V5 hits & misses where I'd expect them.  Initial purges seem to be working.  more testing to come ...

> once the release is out, you can switch to a normal require of ^2.0.0 of the bundle and remove the line about the library again.

noted

**Comment by dbu** [comment]
thanks for the feedback. is it ok for you if we close this issue?

**Comment by pgnd** [comment]
> close this issue?

Sure -- your answer was clear, and the issue goes away in this case soon-ish, anyway.

I'll take care of it.  Thx.
