### ISSUE TITLE
Dependency of php-http/client-implementation

### ISSUE THREAD

**Issue by luebke** [FriendsOfSymfony/FOSHttpCache#374]
The dependency of php-http/client-implementation is broken. The package is not available.

- friendsofsymfony/http-cache 2.0.2 requires php-http/client-implementation ^1.0.0 -> no matching package found.

- friendsofsymfony/http-cache 2.0.1 requires php-http/client-implementation ^1.0.0 -> no matching package found.

- friendsofsymfony/http-cache 2.0.0 requires php-http/client-implementation ^1.0.0 -> no matching package found.

**Comment by dbu** [comment]
php-http/client-implementation is a virtual package. see http://docs.php-http.org/en/latest/httplug/users.html - you need to install one of the adapters.
