### ISSUE TITLE
UserContextListener set http method wrong

### ISSUE THREAD

**Issue by blankse** [FriendsOfSymfony/FOSHttpCache#377]
I try to integrate the FOSCommentBundle in a eZ Platform installation.
In dev environment it works. But in prod environment (without varnish) the UserContextListener makes me problems.

It set with the $request->isMethodSafe() function the method of the request.
(https://github.com/FriendsOfSymfony/FOSHttpCache/blob/master/src/SymfonyCache/UserContextListener.php#L107)

But the FOSCommentBundle used PATCH and PUT methods and at this moment the self::$httpMethodParameterOverride variable is not set to true.
(https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Request.php#L1206)

This happens later in the FrameworkBundle.
(https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/FrameworkBundle.php#L65)

How can I handle this? Is this a bug of this repository?

**Comment by dbu** [comment]
hi, the symfony cache listeners are executed by the symfony HttpCache. at that point, the symfony kernel and the configuration are not yet loaded, so symfony configuration can not be applied.

what is the problem you see? the listener checks if the request is safe (that is, if its cacheable at all - only GET and HEAD requests are cacheable). PATCH and PUT are not safe, so nothing should happen. or does the FOSCommentBundle send GET requests with some magic request attribute to tell they are to be treated as PATCH / PUT?

**Comment by blankse** [comment]
The FOSCommentBundle send a POST request with an _method param set to PUT.

The listener set the request method to POST with the isMethodSafe() call.

Later in the RouterListener (the second method call) the method is still POST and no route is found.

Is it possible to set the method back to null after the isMethodSafe() call? Or clone the request before?

**Comment by dbu** [comment]
ah, web browsers and the need to do horrible things :-/

i was totally not aware of this side effect. yeah i guess we should somehow reset this. is resetting the method to `null` always safe? cloning sounds like it could have bad side effects with large requests...

**Comment by dbu** [comment]
or would it be better to not call that method and just check the "real" request method without triggering side effects?

**Comment by blankse** [comment]
> or would it be better to not call that method and just check the "real" request method without triggering side effects?

I think this would be better.

The method attribute is protected and i think the setMethod function is not a good idea.
