### ISSUE TITLE
[2.1] Will 2.1 support Symfony 2?

### ISSUE THREAD

**Issue by andrerom** [FriendsOfSymfony/FOSHttpCache#384]
Seeing [psr6-symfony-http-cache-store](https://github.com/Toflar/psr6-symfony-http-cache-store/blob/master/composer.json) requiring `symfony/http-kernel` and `symfony/http-foundation` `^3.0`.

Should we:
A. bump requirements here as well?
or
B. stabilize the storage to add 2.x support for those components?

No real opinion from my side, we'll use symfony 3.4+ with FOSHttpCache 2.x ourselves.

**Comment by dbu** [comment]
lets drop old symfony versions and aim for 3.3 (if no issue), 3.4 and 4.0 i would say. users that did not update symfony can keep using 2.0. we have to remember to put bugfixes into the 2.0 version but that should be manageable.
