### ISSUE TITLE
Tags being incorrectly(?) escaped when using Varnish's Xkey module

### ISSUE THREAD

**Issue by PeteLawrence** [FriendsOfSymfony/FOSHttpCache#420]
Currently when Varnish::invalidateTags($tags) is called, the tags contained within $tags are all escaped using preg_quote. eg. `$escapedTags = array_map('preg_quote', $this->escapeTags($tags));`
  
This makes sense when invalidating tags using the original BAN method since the contents of the X-Cache-Tags header gets used in a regular expression match within the fos_ban.vcl file, but not when using the new Xkey method, as the escaped tag may no longer match the original tag if it contains any special characters.

eg. We tag an API response containing details of a particular customer with a tag of 'customer-1234', however when we try to invalidate this tag, the tag becomes 'customer\\-1234' within the invalidation request that gets made to Varnish, and as a result the API response does not get cleared.

I'll happily create a PR if others agree that this is how it should be working, and not me misunderstanding something.

**Comment by dbu** [comment]
oh no, i think you are right. very happy if you can fix this, yes.

can you expand on the functional test for tag invalidation? https://github.com/FriendsOfSymfony/FOSHttpCache/blob/master/tests/Functional/CacheInvalidatorTest.php

ideally first push with just the failing test, then add a commit to fix the problem. i wonder if we should make this yet another configuration... seems like in the end almost all behaviour of the tag invalidator changes based on whether we use BAN or xkey :-/ but i guess we need to make escaping optional, defaulting to true but switching to false in the bundle when xkey mode is used.

**Comment by PeteLawrence** [comment]
I'm not sure there's any value in adding an option to enable/disable escaping is there?  I can't see that you'd ever want to disable it when using BAN's, and nor would you want to enable it when using XKey.

**Comment by dbu** [comment]
agreed. so you would make it dependent on the mode that is selected? i agree with that. want to do a pull request?

**Comment by XWB** [comment]
`X-Cache-Tags header gets used in a regular expression match within the fos_ban.vcl file, but not when using the new Xkey method`

I'm not yet familiar with xkey, but can't we use a regular expression in fos_tags_xkey.vcl was well?

**Comment by dbu** [comment]
no, because the xkey module builds an efficient tree to lookup all cache entries having a specific tag. it can not do fuzzy matching - but its not needed. we use regex for BAN tags because there is a single tag header with all tags.

**Comment by dbu** [comment]
fixed in #421

**Comment by XWB** [comment]
👍
