### ISSUE TITLE
Introduction of PurgeAllCapable?

### ISSUE THREAD

**Issue by Toflar** [FriendsOfSymfony/FOSHttpCache#435]
Sometimes it would be really nice to just purge the whole reverse proxy cache.
Right now this doesn't seem possible because you always have to either purge by tags or URL
Sure, I could just tag every response with the `fos-cache-purge-all` tag and then purge this one but I don't think it's a good idea to just tag them all. I mean, I'm not sure if it is or not, hence this issue.

For the Symfony Proxy Client it could just purge the `http_cache` folder, so that would be easy to implement and definitely more efficient that tagging all the responses. However, I'm not sure about Varnish. Is there anything more efficient you think?
Seems like for Litespeed this would also be the recommended way to go: https://www.litespeedtech.com/support/forum/threads/resolved-ls-cache-purge-all-php-script.14921/

Wdyt?

**Comment by dbu** [comment]
with varnish, you can ban without criteria. this is not super efficient, but its only one single purge request. usually i restart the varnish process, to reset everything.

i am not so sure if it would make sense that the web application itself can do a complete reset. it feels like there are few valid use cases. with the symfony cache kernel, people can build their own solution and with varnish they can ban everything or trigger a restart. therefore i feel like we should rather not have this in the library.

**Comment by Toflar** [comment]
So maybe a bit more background: For Contao and basically any CMS that integrates the FOSCacheBundle and sticks to sending the correct response headers, the huge advantage is that you can configure any reverse proxy the bundle supports. So you can start off small with Symfony and later when traffic grows go bold and switch to Varnish. The CMS supports both of them because it uses the FOSHttpCacheBundle services to tag, invalidate etc. So imho it must be the same for eZ here.
And for any CMS one thing applies: Users manage content and not we as administrators do. So I have to give them some maintenance tasks they can execute when they create new content. One of which is to clear the whole reverse proxy cache.
What it currently does in Contao is it clears the `http_cache` folders content which means that maintenance job is useless if you use the Varnish configuration. So what it should do instead is asking the `CacheInvalidator` (or `CacheManager`) to just `::invalidateAll()` and in case of Symfony it would purge the folder and in case of Varnish it would send the respective request etc.

See where I'm coming from?

**Comment by dbu** [comment]
okay, i see your point. and we can provide a generic way of doing this. 

should we add a ClearCapable interface for the proxy clients, and implement that where possible? and CacheInvalidator can check if a proxy client is ClearCapable (or BanCapable and fallback to BAN everything) to support `clearCache` (i would not call it `invalidateAll` because it sometimes not just invalidates but completely removes the cache entries).

for the symfony proxy, it only works with the same-process client. the client sending web requests can't support this i think, as it does not support BAN.

**Comment by Toflar** [comment]
Maybe tagging every cacheable response with a general tag makes more sense as it's supported in all caches.

**Comment by dbu** [comment]
but that could push the tag system to its extremes, as you might have a huge number of documents with the same tag. and deleting all files one by one could be expensive and freeze quite a bit, compared to delete everything within a folder.

**Comment by Toflar** [comment]
I've hacked a little so we have some code to discuss on. Let's see what you think in https://github.com/FriendsOfSymfony/FOSHttpCache/pull/437.

**Comment by dbu** [comment]
merged in #440
