### ISSUE TITLE
Version 2.5.3 breaks console application

### ISSUE THREAD

**Issue by leofeyer** [FriendsOfSymfony/FOSHttpCache#438]
The new `ProxyUnreachableException` exception which has been added in 7ca3f9e104d3bdc35b6fcdb3cdd57086929006ab yesterday breaks my console application. I think it is fine not to have an HTTP cache on the command line, therefore this case needs to be handled differently IMHO.

**Comment by Toflar** [comment]
Imho that's not a bug of FOSHttpCache. Invalidation should just not happen in this case. I mean you now get an exception but before you should have gotten a `on a null object` error because it was always `null` 😄

**Comment by leofeyer** [comment]
Then maybe this is a problem of the `InvalidationListener` of the bundle?

https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/db0ed59150fc47b347d0d820b411c188b5435d9d/src/EventListener/InvalidationListener.php#L125-L130

**Comment by dbu** [comment]
ah, i think i see the problem. before, we did a loop. if there are 0 elements, the loop would never try to call anything on `null`. i think that exception should only be thrown if there are > 0 invalidation messages to be sent. I will make a fix.

**Comment by leofeyer** [comment]
Thank you @dbu.

**Comment by dbu** [comment]
fixed in 2.5.4
