### ISSUE TITLE
FOSHttpCache not compatible with httplug 2.0.0

### ISSUE THREAD

**Issue by hoebelix** [FriendsOfSymfony/FOSHttpCache#445]
Hi,

I tried to install FOSHttpCache with:

composer require php-http/guzzle6-adapter
composer require friendsofsymfony/http-cache

The second composer command gives the error message:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install friendsofsymfony/http-cache 2.5.4
    - Conclusion: don't install friendsofsymfony/http-cache 2.5.3
    - Conclusion: don't install friendsofsymfony/http-cache 2.5.2
    - Conclusion: don't install friendsofsymfony/http-cache 2.5.1
    - Conclusion: don't install friendsofsymfony/http-cache 2.5.0|remove php-http/httplug v2.0.0
    - Conclusion: don't install friendsofsymfony/http-cache 2.5.0|don't install php-http/httplug v2.0.0
    - Installation request for friendsofsymfony/http-cache ^2.5 -> satisfiable by friendsofsymfony/http-cache[2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.5.4].
    - friendsofsymfony/http-cache 2.5.0 requires php-http/client-common ^1.1.0 -> satisfiable by php-http/client-common[1.3.0, 1.5.0, 1.7.0, 1.8.0, 1.8.1, 1.8.2, 1.9.0, v1.1.0, v1.2.0, v1.2.1, v1.4.0, v1.4.1, v1.4.2, v1.6.0].
    - php-http/client-common v1.1.0 requires php-http/httplug ^1.0 -> satisfiable by php-http/httplug[v1.0.0, v1.1.0].
    - php-http/client-common v1.2.0 requires php-http/httplug ^1.0 -> satisfiable by php-http/httplug[v1.0.0, v1.1.0].
    - php-http/client-common v1.2.1 requires php-http/httplug ^1.0 -> satisfiable by php-http/httplug[v1.0.0, v1.1.0].
    - php-http/client-common 1.3.0 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
    - php-http/client-common 1.5.0 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
    - php-http/client-common 1.7.0 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
    - php-http/client-common 1.8.0 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
    - php-http/client-common 1.8.1 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
    - php-http/client-common 1.8.2 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
    - php-http/client-common 1.9.0 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
    - php-http/client-common v1.4.0 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
    - php-http/client-common v1.4.1 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
    - php-http/client-common v1.4.2 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
    - php-http/client-common v1.6.0 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
    - Can only install one of: php-http/httplug[v1.0.0, v2.0.0].
    - Can only install one of: php-http/httplug[v1.1.0, v2.0.0].
    - Installation request for php-http/httplug (locked at v2.0.0) -> satisfiable by php-http/httplug[v2.0.0].

Installation failed, reverting ./composer.json to its original content.

**Comment by XWB** [comment]
I think you will have to wait for https://github.com/FriendsOfSymfony/FOSHttpCache/pull/442

**Comment by dbu** [comment]
yep, thanks for the link. the release should happen this week i'd say, so soon, soon :-)
