### ISSUE TITLE
xkey purged but still serving cached response

### ISSUE THREAD

**Issue by jonbev** [FriendsOfSymfony/FOSHttpCache#448]
Looking at the logs I can see that the xkey-purge is purging objects - "RespReason     Purged 27 objects, expired 0 objects" but we are still seeing cached responses that are tagged in this example this "property-235". It seems to work ok sometimes as we have two servers running the same ami on amazon and we see this issue with only one of the servers, also some objects with the same tag are correctly purged but others are not. If we replace the server it will work ok for a time and then fail again. I'm not sure how we can debug this as we can't reliably reproduce the problem. 

Is there a way to list objects that have a certain tag?

Any suggestions on how to debug this?

*   << Request  >> 31474814  
-   Begin          req 31474813 rxreq
-   Timestamp      Start: 1554714883.640552 0.000000 0.000000
-   Timestamp      Req: 1554714883.640552 0.000000 0.000000
-   ReqStart       10.100.1.50 38442 a0
-   ReqMethod      PURGEKEYS
-   ReqURL         /
-   ReqProtocol    HTTP/1.1
-   ReqHeader      Host: xxxx.api.tabs-software.co.uk
-   ReqHeader      User-Agent: GuzzleHttp/6.3.3 curl/7.47.0 PHP/7.1.27-1+ubuntu16.04.1+deb.sury.org+1
-   ReqHeader      xkey-purge: property-235 property-235 property
-   ReqHeader      Connection: Close
-   ReqHeader      X-Forwarded-For: 10.100.1.50
-   VCL_call       RECV
-   ReqUnset       X-Forwarded-For: 10.100.1.50
-   ReqHeader      X-Forwarded-For: 10.100.1.50
-   ReqHeader      CloudFront-Forwarded-Proto: https
-   VCL_acl        MATCH invalidators "10.100.1.0"/24
-   ReqHeader      n-gone: 0
-   ReqHeader      n-softgone: 0
-   ReqUnset       n-gone: 0
-   ReqHeader      n-gone: 27
-   VCL_return     synth
-   VCL_call       HASH
-   VCL_return     lookup
-   Timestamp      Process: 1554714883.640706 0.000154 0.000154
-   RespHeader     Date: Mon, 08 Apr 2019 09:14:43 GMT
-   RespHeader     Server: Varnish
-   RespHeader     X-Varnish: 31474814
-   RespProtocol   HTTP/1.1
-   RespStatus     200
-   RespReason     OK
-   RespReason     Purged 27 objects, expired 0 objects
-   VCL_call       SYNTH
-   RespUnset      Server: Varnish
-   RespUnset      X-Varnish: 31474814
-   RespHeader     X-Cache-Action: SYNTH
-   VCL_return     deliver
-   RespHeader     Content-Length: 233
-   Storage        malloc Transient
-   RespHeader     Accept-Ranges: bytes
-   RespHeader     Connection: close
-   Timestamp      Resp: 1554714883.640742 0.000190 0.000036
-   ReqAcct        212 0 212 175 233 408
-   End            

![image](https://user-images.githubusercontent.com/2034227/55715755-5209b580-59ed-11e9-8846-804d9b050d3f.png)

**Comment by dbu** [comment]
not sure if i can help, this sounds like it would potentially be a varnish issue rather than one of this php library. but lets try:

* is this two servers load balanced to serve the same thing? do you send invalidation requests to all servers directly, or only to the load balancer? you need to send to every single cache node - this is the reason why we have this configuration for multiple cache servers. i also once implemented my own invalidator with a message queue when we had an autoscaling system where the application could not know all caches. each cache instance started a php command that listened on the queue and used FOSHttpCache again to invalidate the varnish on localhost.
* do you see in the logs of the other server if it also got invalidation requests?

**Comment by jonbev** [comment]
Thanks for replying. 

Yes the servers are load balanced but i am 100% sure that both servers are receiving all invalidation requests. To make absolutely sure of this I have reduced the servers down to one and tested again and got the same results.

The log in my first message was from the same server as the response showing the cache hit. 

We are also logging purgekeys requests to elasticsearch via logstash so we can see that both servers get the invalidations.

I can see for example that the /property/235 endpoint has its cache cleared but the /property/235/booking doesn't even though they are both tagged with property-235.

I can also test it with other properties and the property/{id}/booking endpoint is actually cleared.

**Comment by dbu** [comment]
strange. i would be surprised if varnish has a bug with that, and with what you say can't see anything wrong with what FOSHttpCache does.

is it possible that you have a race condition? like your storage is only updated with some delay, so you could end up with this flow of events?

* [varnish] xkey invalidated
* [varnish] data requested through varnish, recreating the old state in cache
* [backend] storage updated

**Comment by jonbev** [comment]
Unfortunately not the cache age on the response remains high.

**Comment by dbu** [comment]
then i fear you need to try to see if varnish can help you. i don't know how i could further help you.

**Comment by jonbev** [comment]
Ok thanks for trying.
