### ISSUE TITLE
Generic CDN support

### ISSUE THREAD

**Issue by diimpp** [FriendsOfSymfony/FOSHttpCache#457]
Hello,

I'm tasked with implementing CloudFlare cache invalidation and I've noticed, that `HttpProxyClient` design is not really compatible with generic CDN cache invalidation flow.

What usually happens with CDN is rest post request with json body. Single or multiple urls, headers, etc.

And for example it's not possible to supply body to the request factory of the HttpProxyCache
https://github.com/FriendsOfSymfony/FOSHttpCache/blob/master/src/ProxyClient/HttpProxyClient.php#L94

I do realise, that I can just implement `ProxyClient` interface and do the rest of the implementation as I need to.
And that `HttpProxyClient` is not generic solution, but a specialized version for direct communication with proxy servers line nginx or varnish, but it's kind of feels wrong to have `HttpProxyClient` name wise, while it doesn't allow to send body.

Not sure what this issue is about. :) RFC for renaming `HttpProxyClient`? Add some mention on CDN's or custom ProxyClient implementation?

CF purge request looks like so
```bash
curl -X POST "https://api.cloudflare.com/client/v4/zones/023e105f4ecef8ad9ca31a8372d0c353/purge_cache" \
     -H "X-Auth-Email: user@example.com" \
     -H "X-Auth-Key: abcdefg" \
     -H "Content-Type: application/json" \
     --data '{"files":["http://www.example.com/css/styles.css",{"url":"http://www.example.com/cat_picture.jpg","headers":{"Origin":"cloudflare.com","CF-IPCountry":"US","CF-Device-Type":"desktop"}}]}'
```

Related https://github.com/FriendsOfSymfony/FOSHttpCache/issues/142
https://github.com/FriendsOfSymfony/FOSHttpCache/pull/403

**Comment by dbu** [comment]
hi, great to hear this! @andrerom is looking into fastly support (see #451), which is also a CDN. i think he noticed similar needs. @Toflar is working on litespeed support (see #444), which again asks us to make some concepts more flexible. i would love for FOSHttpCache to be more flexible for these scenarios. please start by looking at the fastly PR to see if that already addresses some of your concerns. we could also extract some refactorings from there and merge early (e.g. allow request body), so that you both can continue the work on CDN support.

**Comment by andrerom** [comment]
Once #451 is in, we can consider adding the following which now seems to have cache tagging support:
- Akamai: https://developer.akamai.com/blog/2019/03/25/introducing-ability-purge-cache-tag
- CloudFlare: https://support.cloudflare.com/hc/en-us/articles/200169246-Purging-cached-resources-from-Cloudflare#h_6d756ac9-c476-45e8-a5d4-e2a6e45d9dc7
- KeyCDN: https://www.keycdn.com/api#purge-zone-tag

**Comment by simonrjones** [comment]
I've added Cloudflare support for a project we're working on and it would be great to add this into FOSHttpCache. Not sure if I should add a new issue, but I thought I'd comment here since this issue seems related.

https://github.com/FriendsOfSymfony/FOSHttpCache/pull/507

**Comment by diimpp** [comment]
`HttpProxyClient` allows to send body since https://github.com/FriendsOfSymfony/FOSHttpCache/pull/451 and library have two CDN integrations since then: Fastly and CloudFlare.

Seems issue is solved now. :fire:

**Comment by dbu** [comment]
thanks @simonrjones - lets discuss the addition in your PR directly, no need for an issue for that ;-)

and thanks @diimpp for cleaning up here.
