### ISSUE TITLE
Varnish's Vary shouldn't include the user context header

### ISSUE THREAD

**Issue by dkarlovi** [FriendsOfSymfony/FOSHttpCache#458]
Once Varnish is returning the response, it will include the user context header too:

```
Vary: Accept-Encoding, Accept, X-User-Context-Hash, Accept-Language, Authorization
```

IIUC, since the `X-User-Context-Hash` header is private, it's never exposed to outside of Varnish. This means it shouldn't be advertised in the `Vary` header either.

**Comment by dbu** [comment]
yes, while it should not be harmful, it is useless and leaking internal information.

if you use the VCL fragment that we provide for including, the vary header is cleaned up, unless you enabled debugging:

https://github.com/FriendsOfSymfony/FOSHttpCache/blob/56dd01d382f390a866aed955f10f09f28b58dd6e/resources/config/varnish/fos_user_context.vcl#L91-L102

**Comment by dkarlovi** [comment]
> unless you enabled debugging

I missed that part, sorry. :see_no_evil:

**Comment by dbu** [comment]
no worries, glad i could help :-)
