### ISSUE TITLE
Unknown parameter "vcl_dir"

### ISSUE THREAD

**Issue by ddeboer** [FriendsOfSymfony/FOSHttpCache#461]
In Varnish 5.1, `vcl_dir` was [deprecated](https://github.com/varnishcache/varnish-cache/blob/master/doc/changes.rst#varnish-cache-510-2017-03-15) in favour of `vcl_path`. Varnish 6.2 [removes the deprecated parameter](https://github.com/varnishcache/varnish-cache/blob/master/doc/changes.rst#varnish-cache-620-2019-03-15).

Unfortunately, we’re still supporting old Varnish versions (even 3). So either we drop support < 5.1 or we have to differentiate and use `vcl_dir` for old versions and `vcl_path` for new ones.

**Comment by dbu** [comment]
i'd prever to support both. if this was only about varnish 3 i would consider dropping support for that, but if it also is about varnish 4 and 5.0, i'd prefer to chose the right thing. do you want to work on that? we already have the phpunit env variable for the varnish version, right?

**Comment by dbu** [comment]
we adjusted the VarnishProxy test tool to support both.
