### ISSUE TITLE
Symfony 4.3 deprecated messages

### ISSUE THREAD

**Issue by XWB** [FriendsOfSymfony/FOSHttpCache#462]
> User Deprecated: The "FOS\HttpCache\Event" class extends "Symfony\Component\EventDispatcher\Event" that is deprecated since Symfony 4.3, use "Symfony\Contracts\EventDispatcher\Event" instead.

> User Deprecated: Calling the "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as first argument is deprecated since Symfony 4.3, pass it second and provide the event object first instead.

**Comment by dbu** [comment]
if you have time to add the fix for this, please create a pull request. we need to be careful not to break older versions of symfony - this is "only" a warning - though it needs to be adressed for symfony 5 support.

**Comment by dbu** [comment]
is dispatching the event really in the library and not in the FOSHttpCacheBundle?

**Comment by XWB** [comment]
@dbu The dispatching error was triggered by https://github.com/FriendsOfSymfony/FOSHttpCache/blob/master/src/CacheInvalidator.php#L309-#L311 so yes, this library is affected. There may be more places.

**Comment by dbu** [comment]
oh, okay then its indeed here and not in the bundle. do you have time to do a PR to change it? we need to check if the new syntax is available (by checking if the dispatcher implements EventDispatcherInterface, if it does we should switch, otherwise we have to use the old order.)

**Comment by XWB** [comment]
@dbu Fixes are available in https://github.com/FriendsOfSymfony/FOSHttpCache/pull/463 and https://github.com/FriendsOfSymfony/FOSHttpCache/pull/464
