### ISSUE TITLE
Question/varnish: Is it possible to ban by tags for a domain?

### ISSUE THREAD

**Issue by flyinggecko** [FriendsOfSymfony/FOSHttpCache#476]
Hi,

We have the usecase to ban and by tags for specific domains which means something like this:
```php
$cacheInvalidator->invalidate($domains)->invalidateTags($tags);
```
This doesn't work, as the the proxy client is sending 2 requests to the varnish, but I hope this explains my usecase.

Now, is it possible to do that already without crafting everything by hand and then sending the request?
And if it is not possible, are you maybe interested in such a functionality?

Bests

**Comment by dbu** [comment]
there are 2 ways of handling tags in varnish: BAN with a regex to match the tags header, and the xkey system. xkey is a varnish native functionality to handle keys and massively more efficient than the BAN based approach. afaik when using xkeys, there is no way to limit invalidation by domain. with BAN, one can specify multiple headers that must match.

one way to handle your requirement could be to include the application name (maybe just the domain name) in the tags, both while tagging and when invalidating. you could decorate those components of FOSHttpCache and replace the services with your decorated version to add the domain prefix to each tag transparently for the rest of your application.

i don't think such functionality belongs into this library, the use case is rather specific. but if there is some place where the library is not flexible enough to allow you to hook such a thing, i am happy to discuss how to keep things flexible.

**Comment by flyinggecko** [comment]
Hey, thank you. I think we need to do this then.
