### ISSUE TITLE
PHP 8.0 compatibility

### ISSUE THREAD

**Issue by ausi** [FriendsOfSymfony/FOSHttpCache#487]
Are there any plans for adding compatibilty with PHP 8.0?

Would you like me to create a pull request for this?

**Comment by dbu** [comment]
yes please. and this one should be easier than the cmf stack, i hope.

**Comment by Toflar** [comment]
I think the phpunit stuff will be PITA. @dbu maybe it's time for a new major version here too? Drop all the stuff that's Symfony < 4.4 just like I did for the PSR-6 store? I mean, you're the main maintainer of that lib but imho PHP 8 would be reason enough to finally get rid of the old stuff and lower the maintenance burden on your side?

**Comment by dbu** [comment]
i don't mind dropping support for php 7.1 and symfony < 4.4 if that helps. i don't know how deeply we go into symfony, not sure if removing symfony 3.4 support makes much of a difference.

doing that does not require a new major version, just a new minor version. as long as we don't change any interface signatures / method signatures. it would be nice to start doing strict typing, but maybe better do that later and for now focus on getting a php 8 supporting release out.

**Comment by ausi** [comment]
Closed in favor of #488
