### ISSUE TITLE
move build to github actions

### ISSUE THREAD

**Issue by MedUnes** [FriendsOfSymfony/FOSHttpCache#492]

**Comment by dbu** [comment]
agreed that would be useful. do you have time to do a pull request?

**Comment by MedUnes** [comment]
Yes sure, should I prepare one that does the current job of travis one ?

**Comment by dbu** [comment]
that would be awesome, yes. when you fork this repo, github will start building in your fork, so we can immediately see if it works.

if you need inspiration, i quite like what we did in the php-http projects: https://github.com/php-http/httplug/blob/master/.github/workflows/ . the extra challenge for FOSHttpCache is that we have to install a couple of applications like varnish for the functional tests...

**Comment by dbu** [comment]
@MedUnes do you have time to work on converting the test setup to github actions?

**Comment by dbu** [comment]
FTR: i strated working on this in #500

**Comment by dbu** [comment]
everything moved to github actions except for the phpunit tests. the varnish setup is tricky...
