### ISSUE TITLE
Any plans for tagging support for other caching proxies (Nginx, ...)?

### ISSUE THREAD

**Issue by hoebelix** [FriendsOfSymfony/FOSHttpCache#523]
Hello,

in your README you write "Cache tagging abstraction, uses BAN with Varnish and allows tagging support for other caching proxies in the future". Are there any plans for adding tagging support for Nginx?

Thank you!

**Comment by Toflar** [comment]
You can find the overview of [supported proxies in the docs](Fixes https://github.com/contao/docs/issues/885).
Afaik Nginx does not support cache tagging, hence it's not implemented in this library either.

**Comment by hoebelix** [comment]
Yes, I know that Nginx does not support caching out of the box. But tag support could be provided by this module. The idea would be to record the relation tags <-> uris in a local database and then use this data to support invalidation by tags. 

At least this was my interpretation of "support for other caching proxies in the future".

**Comment by hoebelix** [comment]
Ok, thank you.

**Comment by dbu** [comment]
thanks @hoebelix for bringing this up. the readme was indeed a bit unclear, and also missing to list a couple of supported systems. i reformulated it now.

**Comment by hoebelix** [comment]
Thanks! But nonetheless it would be a killer feature if tagging support could be emulated by this library for proxies that don't support it.

Why? Most of the mid-sized setups will have php-fpm running behind Nginx. So Nginx is already there. This library could then be used without adding more complexity on the infrastructure part (in the form of varnish etc.).

**Comment by dbu** [comment]
the nginx purge support is done with installing a plugin: https://github.com/FRiCKLE/ngx_cache_purge

if you know a good plugin for cache tagging, you are welcome to contribute an integration to that. i am happy to help guide you where in FOSHttpCache this can be enabled, but myself don't use nginx so i don't know that part well.

**Comment by hoebelix** [comment]
Yes, I know ngx_cache_purge, but this does not support cache tagging. As far as I know there is no well-established plugin that supports tagging.

So my idea would be the following: This library hooks into the request-response cycle and reads the tags from the headers of the response. The resulting data (uri, tags) is then stored in a local database. On invalidation requests this data is then read from the database and multiple invalidation requests would be send to nginx.

Example:
Say we have to uris with two tags respectively:

/article-germany with tags europe, germany
/article-france with tags europe, france

This would yield the following data in a database

```
/article-germany     | europe
/article-germany     | germany
/article-france      | europa
/article-france      | france
```

When there is an invalidation request for the tag europe, this would result in two invalidation requests: one for /article-germany, one for /article-france.

**Comment by Toflar** [comment]
Having two separate caches for the entries (nginx) and the tags (your local database) might end up in lots of orphaned tags as your local cache is not informed if nginx deletes a cache entry (because it expired or any other service purged it). So I'm not entirely sure this is a good idea but it sure would be possible. You might want to give it a try :)

**Comment by hoebelix** [comment]
Yes, Toflar you are right with the orphaned entries in the database. But this could be avoided:

- all rows for an uri must be deleted after invalidation of this uri
- every row has an expiration timestamp derived from the X-Reverse-Proxy-TTL header. Expired rows must be garbage collected from time to time.

I'll give it a try!

**Comment by dbu** [comment]
i would not want to put that feature into this library nor into the bundle. it would involve quite some code for a very specific case. would then sound more straightforward to me to use the symfony HttpCache if you want cache tagging and only have nginx. that one is well-tested and works ok for small sites.

you are of course free to try, and it can be fun to see how symfony and http work. it should be doable to build that functionality as a separate bundle that integrates with the FOSHttpCache - if you get something going i am happy to link to it from the documentation. but i don't want to integrate all the necessary code into this library and keep maintaining it, sorry.

**Comment by hoebelix** [comment]
Yes, I can understand that. I'll give it a try on my own. In case it emerges to something which others might use as well, I let you know.

**Comment by dbu** [comment]
please do
