### ISSUE TITLE
Guzzle 4

### ISSUE THREAD

**Issue by ddeboer** [FriendsOfSymfony/FOSHttpCache#53]
We could upgrade our Guzzle implementation to their recently released version 4, which allegedly is [faster](http://mtdowling.com/blog/2014/03/15/guzzle-4-rc/). However, it requires PHP 5.4. Can we already drop our PHP 5.3 support? :)

**Comment by joelwurtz** [comment]
When php5.4 will not be a problem, why not using https://github.com/egeloen/ivory-http-adapter ? 

This way, user can choose which http client to use and avoid having an undetermined number of http client library in his project ^^

**Comment by ddeboer** [comment]
@joelwurtz :stuck_out_tongue_winking_eye:

**Comment by andrerom** [comment]
Abstractions of the abstractions :)

Anyone up for proposing a PSR for the missing HTTPClientInterface (building upon PSR-7)? If we had that this discussion would be moot ;)

**Comment by ddeboer** [comment]
We’ll be adding support for newer Guzzle versions through the HTTP client adapter in 2.0 (#173).
