### ISSUE TITLE
Varnish 7 support

### ISSUE THREAD

**Issue by kbentlage** [FriendsOfSymfony/FOSHttpCache#535]
Hi There,

A customer of ours is using the FOS cache VCLs for Varnish Caching.

On the most recent version of Varnish, Varnish 7, the caching does not work at all.

I am wondering if Varnish 7 is already supported?

**Comment by dbu** [comment]
there is a CI build with varnish 7: https://github.com/FriendsOfSymfony/FOSHttpCache/blob/b20ba13dec0b3d6c0b2ecf692f0b6a6eed6d89fd/.github/workflows/ci.yml#L34

it seems to work. also, if there was a problem i would rather expect to see errors with varnish not accepting the VCL. i fear you need to investigate what is going wrong.

**Comment by jdreesen** [comment]
The README says `Use the built-in support for Varnish versions 3 to 6`. Should it be changed to include `7`?

**Comment by dbu** [comment]
oh, i forgot to update the readme. i removed version numbers there, we also don't give them for nginx etc: https://github.com/FriendsOfSymfony/FOSHttpCache/commit/652f4f521fba4b5f087714b30ea646bfec66a4ba
