### ISSUE TITLE
Incompatibility with `symfony/framework-bundle` in `2.16.0` via `EventDispatchingHttpCache::forward`

### ISSUE THREAD

**Issue by fritzmg** [FriendsOfSymfony/FOSHttpCache#581]
In `2.16.0` the `forward()` method was added to the `EventDispatchingHttpCache` trait (https://github.com/FriendsOfSymfony/FOSHttpCache/commit/c19bdcff595675326bedd5d488f2f3f296194f88).

However, this trait is not compatible with all `symfony/framework-bundle` versions. If you use `symfony/framework-bundle` in version `4.4.x` you will get the following error when using the trait in your `HttpCache` class:

```
PHP Fatal error:  Declaration of FOS\HttpCache\SymfonyCache\EventDispatchingHttpCache::forward(Symfony\Component\HttpFoundation\Request $request, bool $catch = false, ?Symfony\Component\HttpFoundation\Response $entry = null): Symfony\Component\HttpFoundation\Response 
must be compatible with 
Symfony\Bundle\FrameworkBundle\HttpCache\HttpCache::forward(Symfony\Component\HttpFoundation\Request $request, $raw = false, ?Symfony\Component\HttpFoundation\Response $entry = null)
```

**Comment by dbu** [comment]
oh no, i missed that. phpstan only checks newest version - maybe a low level phpstan on lowest would make sense :thinking: 

i released the fixed version https://github.com/FriendsOfSymfony/FOSHttpCache/releases/tag/2.16.1

**Comment by dbu** [comment]
dang it, merged the fix to the wrong branch :facepalm:  - the actually fixed version is https://github.com/FriendsOfSymfony/FOSHttpCache/releases/tag/2.16.2
