### ISSUE TITLE
Package php-http/message-factory is abandoned

### ISSUE THREAD

**Issue by ro0NL** [FriendsOfSymfony/FOSHttpCache#585]

**Comment by dbu** [comment]
we use the psr-17 factories in version 3: https://github.com/FriendsOfSymfony/FOSHttpCache/blob/3.x/src/ProxyClient/HttpProxyClient.php

do you see what includes the legacy message-factory package? i don't see it in composer.json so it either is something else in your application or a transient dependency and we might want to upgrade one of our dependencies.

**Comment by ro0NL** [comment]
i confused permalinks between 2.x and 3.x (`php-http/message-factory` vs. `psr/http-factory`)

excusi!

**Comment by dbu** [comment]
np, thanks for following up.
